---
title: "forecast_evaluation"
author: "Jeron Tan"
date: "2025-10-25"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(rpart)
library(glmnet)
library(pls)
library(tidyr)
library(openxlsx)
library(hdm)
library(readxl)
```




```{r}
df = read.csv("../data/full_df.csv") %>% mutate(date = as.Date(date, format = "%m/%d/%y")) 
df

```


```{r}
ggplot(df, aes(x = as.Date(date), y = erp * 100)) +
  annotate("rect", xmin = start, xmax = end, ymin = -Inf, ymax = Inf,
           fill = "grey50", alpha = 0.15) +
  geom_line(color = "blue") +   # blue line
  annotate("text", x = x_text_right, y = y_text,
           label = "Evaluation Period from 2015:5 to 2023:8",
           hjust = 0, size = 3) +
  annotate("text", x = x_text_left, y = y_text,
           label = "Train/Validation Period from 1996:5 to 2015:4",
           hjust = 0, size = 3) +
  labs(title = "", x = NULL, y = "") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
ggplot(df, aes(x = erp * 100)) +
  geom_histogram(bins = 30, color = "white") +
  geom_density(aes(y = after_stat(density)), linewidth = 1) +
  labs(title = "Distribution of ERP", x = "ERP (%)", y = "Density") +
  theme_minimal() +
    theme(
    plot.title = element_text(hjust = 0.5)
    )
```

```{r}
ggplot(df, aes(x = erp * 100)) +
  geom_histogram(
    aes(y = after_stat(count / sum(count))),
    bins = 30,
    fill = "steelblue",  
    color = "white"      
  ) +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_x_continuous(
    breaks = scales::breaks_width(5),
    labels = function(x) paste0(x, "%")
  ) +
  labs(title = "",
       x = "Monthly ERP (%)", y = "Share (%)") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
x <- df$erp * 100
m <- mean(x, na.rm = TRUE)
s <- sd(x, na.rm = TRUE)

stats <- tibble(
  metric = c("n","mean (%)","median (%)","sd (%)",
             "mean-1sd","mean+1sd","min (%)","p5 (%)","p95 (%)","max (%)"),
  value  = c(
    sum(is.finite(x)),
    m, median(x, na.rm = TRUE), s,
    m - s, m + s,
    min(x, na.rm = TRUE),
    quantile(x, 0.05, na.rm = TRUE),
    quantile(x, 0.95, na.rm = TRUE),
    max(x, na.rm = TRUE)
  )
) |> mutate(value = round(value, 3))

print(stats)
```


