Load packages: 
```{r}
library(randomForest)
library(dplyr)
```

Function for random forest h step ahead forecast. 
To be used in the model code chunk in forecast_evaluation.rmd. 

```{r}
# run this cell to get the tuned mtry values for h=1,3,6,12

h_values <- c(1, 3, 6, 12)
tuning_summary <- data.frame(h = h_values, mtry = NA_integer_, oob_mse = NA_real_)

for (i in seq_along(h_values)) {
  h <- h_values[i]
  df_std = df %>% mutate(across(-c(date, erp), ~ as.numeric(scale(.)))) %>% arrange(date)
  df_std = df_std %>% mutate(target = lead(erp, n = h)) %>% select(date, target, everything())

  df_forecast = df_std %>% slice(n()-h+1)
  df_train = df_std %>% slice(1:(n() - h))

  feats <- setdiff(names(df_std), c("date", "target"))

  x_train <- df_train[, feats, drop=FALSE]
  y_train <- df_train$target

  x_forecast <- df_forecast[, feats, drop=FALSE]
  y_forecast <- df_forecast$target

  set.seed(456857)
  p <- ncol(x_train)

  rf_fit <- tuneRF(
    x = x_train,
    y = y_train,
    mtryStart = floor(sqrt(p)),
    stepFactor=2,
    improve=0.05,
    nodesize=5,
    ntree=5000,
    doBest=TRUE,
    plot=FALSE,
    trace=FALSE,
    importance = TRUE
  )

  tuning_summary$mtry[i]   <- rf_fit$mtry
  tuning_summary$oob_mse[i] <- tail(rf_fit$mse, 1)
}

print(tuning_summary)
```

```{r}
model <- function(df, h) {
  df_std = df %>% mutate(across(-c(date, erp), ~ as.numeric(scale(.)))) %>% arrange(date)
  df_std = df_std %>% mutate(target = lead(erp, n = h)) %>% select(date, target, everything())

  df_forecast = df_std %>% slice(n()-h+1)
  df_train = df_std %>% slice(1:(n() - h))

  feats <- setdiff(names(df_std), c("date", "target"))

  x_train <- df_train[, feats, drop=FALSE]
  y_train <- df_train$target

  x_forecast <- df_forecast[, feats, drop=FALSE]
  y_forecast <- df_forecast$target

  set.seed(456857)
  p <- ncol(x_train)

  # mtry = 8 is tuned value
  rf_fit <- randomForest(
    x = x_train,
    y = y_train,
    ntree=5000,
    mtry = 8,
    importance = TRUE
  )

  pred <- predict(rf_fit, newdata = x_forecast)
  return(pred)
}
```
